spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:loans
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none

##Diabled swagger in production environment
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false